name: flutter_email_sender_example
description: Demonstrates how to use the flutter_email_sender plugin.

version: 1.0.0

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^0.5.0+1
  image_picker: ^0.5.1
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_email_sender:
    path: ../


flutter:
  uses-material-design: true
